### ISSUE TITLE
Exception ignored in: <async_generator object _ag at 0x7f9979703938>

### ISSUE THREAD

**Issue by amal-khailtash** [dropbox/pyannotate#50]
Trying to collect type annotations, but I get this exception

Exception ignored in: <async_generator object _ag at 0x7f9979703938>
Traceback (most recent call last):
  File ".../python/3.6.3/lib/python3.6/types.py", line 27, in _ag
  File ".../.venv/lib/python3.6/site-packages/pyannotate_runtime/collect_types.py", line 752, in _trace_dispatch
  File ".../.venv/lib/python3.6/site-packages/pyannotate_runtime/collect_types.py", line 698, in default_filter_filename
TypeError: startswith first arg must be str or a tuple of str, not NoneType

**Comment by gvanrossum** [comment]
Is the code you are trying to run public?

**Comment by amal-khailtash** [comment]
Unfortunately it is not.  I might be able to share snippets, but not sure what to capture.

**Comment by gvanrossum** [comment]
Hm, it sounds like it's possible for a code object to have None for a
filename. I'll think of a fix for that.
